const {safeStorage,shell}=require('electron');
const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const crypto=require('node:crypto');
const redirect='http://127.0.0.1:49832/callback';
function createConnection(dir){
 const file=path.join(dir,'soundcloud.secure');let saved={};let pending=false,refreshing=null;
 if(fs.existsSync(file)){try{saved=JSON.parse(safeStorage.decryptString(fs.readFileSync(file)));}catch{throw Error('Saved SoundCloud credentials could not be decrypted by this Windows account.');}}
 function persist(){if(!safeStorage.isEncryptionAvailable())throw Error('Windows credential encryption is unavailable.');const temp=file+'.tmp';fs.writeFileSync(temp,safeStorage.encryptString(JSON.stringify(saved)));fs.renameSync(temp,file);}
 function status(){return {configured:!!saved.clientId,connected:!!saved.accessToken,snapshot:saved.snapshot||null};}
 async function token(params){const r=await fetch('https://secure.soundcloud.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:new URLSearchParams({client_id:saved.clientId,client_secret:saved.clientSecret,...params}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`SoundCloud authorization failed (${r.status}). Check your app credentials and redirect address.`);const data=await r.json();if(!data.access_token||!data.refresh_token)throw Error('SoundCloud did not return a complete authorization.');saved.accessToken=data.access_token;saved.refreshToken=data.refresh_token;saved.expires=Date.now()+(data.expires_in||3600)*1000;persist();}
 async function request(url){const u=new URL(url,'https://api.soundcloud.com');if(u.origin!=='https://api.soundcloud.com')throw Error('Unexpected API pagination address.');if(!saved.accessToken)throw Error('Connect your SoundCloud account first.');if(Date.now()>saved.expires-60000){if(!refreshing)refreshing=token({grant_type:'refresh_token',refresh_token:saved.refreshToken}).finally(()=>refreshing=null);await refreshing;}const r=await fetch(u,{headers:{Authorization:'OAuth '+saved.accessToken,Accept:'application/json'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`SoundCloud returned ${r.status}. ${r.status===429?'Rate limit reached. Please try again later.':'Try reconnecting your account.'}`);return r.json();}
 async function sync(){const profile=await request('/me');let tracks=[],next='/me/tracks?linked_partitioning=true&limit=200',pages=0;while(next&&pages++<50){const data=await request(next);tracks.push(...(Array.isArray(data)?data:data.collection||[]));next=Array.isArray(data)?null:data.next_href;}if(next)throw Error('Catalog exceeds this build’s 10,000-track sync limit. Previous snapshot preserved.');saved.snapshot={profile:{username:profile.username,followers_count:profile.followers_count,track_count:profile.track_count},tracks:tracks.map(t=>({id:t.id,title:t.title,sharing:t.sharing,playback_count:t.playback_count,likes_count:t.likes_count,favoritings_count:t.favoritings_count})),syncedAt:new Date().toISOString()};persist();return status();}
 return {status,sync,async upload(file,metadata,options){await request('/me');return require('./upload.cjs').sendUpload(file,metadata,{...options,token:saved.accessToken});},credentials(id,secret){if(pending)throw Error('Finish the current connection attempt first.');if(typeof id!=='string'||typeof secret!=='string'||!id||!secret||id.length>4096||secret.length>4096)throw Error('Enter both your Client ID and client secret.');saved={clientId:id,clientSecret:secret};persist();return status();},disconnect(){if(pending)throw Error('Finish the current connection attempt first.');saved={clientId:saved.clientId,clientSecret:saved.clientSecret};persist();return status();},async authorize(){
  if(!saved.clientId)throw Error('Save your registered app credentials below first.');if(pending)throw Error('An authorization request is already open. Finish it in your browser.');pending=true;
  const verifier=crypto.randomBytes(32).toString('base64url'),state=crypto.randomBytes(32).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url');
  try{await new Promise((resolve,reject)=>{let timer;let handled=false;const finish=err=>{clearTimeout(timer);server.close();err?reject(err):resolve();};const server=http.createServer(async(req,res)=>{
   const url=new URL(req.url,redirect);if(url.pathname!=='/callback'){res.writeHead(404).end();return;}if(handled||url.searchParams.get('state')!==state){res.writeHead(400).end('Invalid authorization state.');return;}handled=true;
   if(!url.searchParams.get('code')){res.writeHead(400).end('Authorization was cancelled. Return to Soundcloud Desktop.');finish(Error('SoundCloud authorization was cancelled.'));return;}
   try{await token({grant_type:'authorization_code',redirect_uri:redirect,code_verifier:verifier,code:url.searchParams.get('code')});res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'"}).end('<html><body style="background:#191a1d;color:#fafafa;font:18px Segoe UI;padding:60px"><h1>SoundCloud connected.</h1><p>You can close this tab and return to Soundcloud Desktop.</p></body></html>');finish();}catch(e){res.writeHead(400).end('Connection failed. Return to the desktop app for details.');finish(e);}
  });server.on('error',e=>finish(Error(e.code==='EADDRINUSE'?'The connection port is in use. Close the other connection attempt and try again.':e.message)));server.listen(49832,'127.0.0.1',()=>{const url=new URL('https://secure.soundcloud.com/authorize');url.search=new URLSearchParams({client_id:saved.clientId,redirect_uri:redirect,response_type:'code',code_challenge:challenge,code_challenge_method:'S256',state}).toString();shell.openExternal(url.toString()).catch(finish);});timer=setTimeout(()=>finish(Error('Connection timed out after five minutes. Try connecting again.')),300000);});return await sync();}finally{pending=false;}
 }};
}
module.exports={createConnection};
