const {_electron:electron}=require('@playwright/test');const assert=require('node:assert/strict');const fs=process.mainModule.require('node:fs');const path=process.mainModule.require('node:path');const os=require('node:os');const http=require('node:http');const {sendUpload}=require('../upload.cjs');const {createStore}=require('../store.cjs');
const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'soundcloud-uploader-test-'));const file=path.join(dir,'Test master.wav');fs.writeFileSync(file,Buffer.alloc(1024*1024,42));let received,app;let mode='ok';
const server=http.createServer((req,res)=>{const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>{received={headers:req.headers,body:Buffer.concat(chunks)};if(mode==='reject'){res.writeHead(422).end('{}');return;}if(mode==='hang')return;res.writeHead(201,{'Content-Type':'application/json'}).end(JSON.stringify({id:123,title:'Test master',sharing:'private',state:'processing',permalink_url:'https://soundcloud.com/test/master'}));});});
async function launch(){app=await electron.launch({...(process.env.APP_EXE?{executablePath:process.env.APP_EXE,args:[]}:{args:[root]}),env:{...process.env,CLOUDROOM_TEST_DATA:dir}});const page=await app.firstWindow();await page.getByRole('heading',{name:'Your next release starts here.'}).waitFor();return page;}
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/tracks`;
let progress=0;const result=await sendUpload(file,{title:'Test master',sharing:'private',artist:'Test artist'},{token:'test-token',url,onProgress:p=>progress=p});assert.equal(result.id,123);assert.equal(progress,100);assert.equal(received.headers.authorization,'OAuth test-token');assert.equal(received.body.length,Number(received.headers['content-length']));assert.ok(received.body.includes(Buffer.from('name="track[asset_data]"')));assert.ok(received.body.includes(fs.readFileSync(file)));assert.ok(received.body.includes(Buffer.from('name="track[sharing]"\r\n\r\nprivate')));
mode='reject';await assert.rejects(sendUpload(file,{title:'bad'},{token:'test',url}),/422/);mode='hang';const abort=new AbortController();const cancelled=sendUpload(file,{title:'cancel'},{token:'test',url,signal:abort.signal});setTimeout(()=>abort.abort(),100);await assert.rejects(cancelled,/cancelled/);mode='ok';
let page=await launch();await app.evaluate(({app,safeStorage},dir)=>{const fs=process.mainModule.require('node:fs');fs.writeFileSync(process.mainModule.require('node:path').join(dir,'soundcloud.secure'),safeStorage.encryptString(JSON.stringify({clientId:'test',clientSecret:'test',accessToken:'test-token',refreshToken:'test-refresh',expires:Date.now()+3600000,snapshot:{profile:{username:'Test artist'},tracks:[],syncedAt:new Date().toISOString()}})));},dir);await app.close();app=null;
const store=createStore(dir);const s=store.read();s.tracks.push({id:'test-track',title:'Test master',file,format:'WAV',size:1024*1024,status:'Mastered',genre:'Electronic',notes:'A test upload',credits:'',link:''});store.write(s);
page=await launch();await app.evaluate(({app},url)=>{globalThis.fetch=async input=>{if(String(input)!=='https://api.soundcloud.com/me')throw Error('Unexpected test request '+input);return {ok:true,json:async()=>({username:'Test artist'})};};const mod=process.mainModule.require(process.mainModule.require('node:path').join(app.getAppPath(),'upload.cjs'));const original=mod.sendUpload;mod.sendUpload=(file,metadata,options)=>original(file,metadata,{...options,url});},url);
await page.locator('nav [data-page=upload]').click();await page.getByRole('button',{name:'Upload track',exact:true}).click();assert.equal(await page.locator('#upload-form select[name=sharing]').inputValue(),'private');await app.evaluate(({dialog},art)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[art]});},path.join(root,'assets/icon.png'));await page.getByRole('button',{name:'Choose cover artwork',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#upload-art-preview img')?.naturalWidth>0);await page.screenshot({path:path.join(root,'tests','upload-details.png')});await page.getByRole('button',{name:'Upload to SoundCloud',exact:true}).click();await page.getByText('UPLOAD ACCEPTED',{exact:true}).waitFor();assert.ok(received.body.includes(Buffer.from('name="track[artwork_data]"')));assert.equal(createStore(dir).read().tracks[0].lastUpload.id,123);await page.screenshot({path:path.join(root,'tests','upload-success.png')});
console.log('PASS: streamed audio bytes and multipart fields, progress, server rejection, cancellation, uploader UI, private default, artwork attachment, upload receipt. SoundCloud server mocked; no real upload performed.');
}catch(e){console.error(e);process.exitCode=1;}finally{if(app)await app.close();server.closeAllConnections();server.close();}})();
