using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Cryptography;
using System.Runtime.InteropServices;
using System.Net;
using System.Net.Sockets;
using System.Web;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Microsoft.Win32;

[assembly:System.Reflection.AssemblyTitle("Soundcloud Desktop")]
[assembly:System.Reflection.AssemblyProduct("Soundcloud Desktop")]
[assembly:System.Reflection.AssemblyVersion("0.1.0.0")]
[assembly:System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0")]

public class Track {public string Id{get;set;} public string File{get;set;} public string Title{get;set;} public string Art{get;set;} public string Link{get;set;} public string Upload{get;set;} public override string ToString(){return Title+"   ·   "+Path.GetExtension(File).TrimStart('.').ToUpperInvariant()+"   ·   "+(Upload??"Not uploaded");}}
public class Release {public string Title{get;set;} public string Date{get;set;} public string Notes{get;set;} public bool Master{get;set;} public bool Artwork{get;set;} public bool Metadata{get;set;} public bool Published{get;set;} public override string ToString(){return Title+"   ·   "+Date;}}
public class Campaign {public string Title{get;set;} public string Contact{get;set;} public string Text{get;set;} public override string ToString(){return Title+"   ·   "+Contact;}}
public class Workspace {public int Version=1;public List<Track> Tracks=new List<Track>();public List<Release> Releases=new List<Release>();public List<Campaign> Campaigns=new List<Campaign>();}
public class Account {public string ClientId,Secret,Access,Refresh,User;public long Expires;}

public static class Program {
 static Mutex mutex;static EventWaitHandle activate;
 [STAThread]public static int Main(string[] args){
  bool first;mutex=new Mutex(true,"Local\\SoundcloudDesktop.Native.SingleInstance",out first);
  if(!first){try{EventWaitHandle.OpenExisting("Local\\SoundcloudDesktop.Native.Activate").Set();}catch{}return 0;}
  activate=new EventWaitHandle(false,EventResetMode.AutoReset,"Local\\SoundcloudDesktop.Native.Activate");
  try{
   Transport.Verify();
   if(args.Length>0&&args[0]=="--verify-transport"){if(Convert.ToInt32(Transport.Request("https://api.soundcloud.com/me",null,null,null,false)["_http"])!=401)return 1;return 0;}
   if(args.Length>0&&args[0]=="--self-test"){SelfTest.Run();return 0;}
   Application app=new Application();Shell shell=new Shell();
   ThreadPool.QueueUserWorkItem(delegate{while(activate.WaitOne()){app.Dispatcher.BeginInvoke(new Action(delegate{shell.Window.Show();if(shell.Window.WindowState==WindowState.Minimized)shell.Window.WindowState=WindowState.Normal;shell.Window.Activate();}));}});
   app.DispatcherUnhandledException+=delegate(object s,System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e){shell.Notify("The action could not finish. Your saved workspace is preserved. "+e.Exception.Message);e.Handled=true;};
   app.Run(shell.Window);return 0;
  }catch(Exception e){if(args.Length>0)return 1;MessageBox.Show(e.Message,"Soundcloud Desktop",MessageBoxButton.OK,MessageBoxImage.Error);return 1;}
  finally{activate.Close();mutex.ReleaseMutex();mutex.Close();}
 }
}

public static class Transport {
 public static string Root=AppDomain.CurrentDomain.BaseDirectory;
 public static volatile Process Active;
 public static Action<int> Progress;
 static string Hash(string p){using(var sha=SHA256.Create())using(var f=File.OpenRead(p))return BitConverter.ToString(sha.ComputeHash(f)).Replace("-","");}
 public static void Verify(){if(Hash(Path.Combine(Root,"curl.exe"))!="57309336350DF718D9D3F76694D86A997BF9DC6708CE2D86B658294707572B3C"||Hash(Path.Combine(Root,"curl-ca-bundle.crt"))!="385AB0F472BD83B54421BEE302F9B841BBAC12310805FCCF7DEBBA16D84FAFD0")throw new Exception("The network helper or certificate bundle is missing or has changed. Re-extract the original application package before connecting.");}
 public static string Quote(string s){return "\""+(s??"").Replace("\\","\\\\").Replace("\"","\\\"").Replace("\r","\\r").Replace("\n","\\n").Replace("\t","\\t")+"\"";}
 public static Dictionary<string,object> Request(string url,string token,Dictionary<string,string> values,string audio,bool requireSuccess){return Request(url,token,values,audio,requireSuccess,null);}
 public static Dictionary<string,object> Request(string url,string token,Dictionary<string,string> values,string audio,bool requireSuccess,string artwork){
  Verify();Uri uri=new Uri(url);if(uri.Scheme!="https"||!(uri.Host=="api.soundcloud.com"||uri.Host=="secure.soundcloud.com"))throw new Exception("Unrecognized SoundCloud endpoint.");
  StringBuilder config=new StringBuilder();config.AppendLine("url = "+Quote(url));config.AppendLine("proto = \"=https\"");config.AppendLine("tlsv1.2");config.AppendLine("http1.1");config.AppendLine("connect-timeout = 30");config.AppendLine("max-time = "+(audio==null?"60":"3600"));config.AppendLine("speed-time = 60");config.AppendLine("speed-limit = 1");config.AppendLine("cacert = "+Quote(Path.Combine(Root,"curl-ca-bundle.crt")));config.AppendLine("header = \"Accept: application/json\"");config.AppendLine("write-out = \"\\nSCD_HTTP:%{http_code}\"");
  if(token!=null)config.AppendLine("header = "+Quote("Authorization: OAuth "+token));
  if(values!=null){config.AppendLine("request = \"POST\"");foreach(var p in values){if(audio==null)config.AppendLine("data-urlencode = "+Quote(p.Key+"="+p.Value));else config.AppendLine("form-string = "+Quote("track["+p.Key+"]="+p.Value));}}
  if(audio!=null){var fi=new FileInfo(audio);if(!fi.Exists||fi.Length==0||fi.Length>4L*1024*1024*1024)throw new Exception("Select a non-empty audio file up to 4 GB.");config.AppendLine("form = "+Quote("track[asset_data]=@\""+audio.Replace("\\","/").Replace("\"","\\\"")+"\""));if(!String.IsNullOrEmpty(artwork))config.AppendLine("form = "+Quote("track[artwork_data]=@\""+artwork.Replace("\\","/").Replace("\"","\\\"")+"\""));config.AppendLine("progress-bar");}else config.AppendLine("silent");
  config.AppendLine("show-error");
  ProcessStartInfo info=new ProcessStartInfo(Path.Combine(Root,"curl.exe"),"-q --config -");info.UseShellExecute=false;info.CreateNoWindow=true;info.RedirectStandardInput=true;info.RedirectStandardOutput=true;info.RedirectStandardError=true;info.StandardOutputEncoding=Encoding.UTF8;info.StandardErrorEncoding=Encoding.UTF8;info.WorkingDirectory=Root;
  using(Process p=new Process()){p.StartInfo=info;p.Start();Active=p;
   Task<string> output=Task.Factory.StartNew(delegate{return p.StandardOutput.ReadToEnd();});
   Task<string> error=Task.Factory.StartNew(delegate{StringBuilder all=new StringBuilder(),line=new StringBuilder();int ch;while((ch=p.StandardError.Read())!=-1){if(all.Length<8192)all.Append((char)ch);if(ch=='\r'||ch=='\n'){var match=System.Text.RegularExpressions.Regex.Match(line.ToString(),@"(\d{1,3})\.\d%" );if(match.Success&&Progress!=null)Progress(Math.Min(100,Int32.Parse(match.Groups[1].Value)));line.Length=0;}else if(line.Length<2000)line.Append((char)ch);}return all.ToString();});
   try{byte[] input=Encoding.UTF8.GetBytes(config.ToString());p.StandardInput.BaseStream.Write(input,0,input.Length);p.StandardInput.Close();p.WaitForExit();string text=output.Result;string err=error.Result;if(p.ExitCode!=0)throw new Exception("Secure transfer did not finish (network code "+p.ExitCode+"). Check the connection and account catalog before retrying. No automatic duplicate upload was attempted.");int marker=text.LastIndexOf("\nSCD_HTTP:",StringComparison.Ordinal);if(marker<0)throw new Exception("The server returned an incomplete response.");int status=Int32.Parse(text.Substring(marker+10).Trim());if(requireSuccess&&(status<200||status>=300))throw new Exception("SoundCloud returned HTTP "+status+". Check your credentials, account quota, and file format.");string body=text.Substring(0,marker);Dictionary<string,object> result;try{result=new JavaScriptSerializer().Deserialize<Dictionary<string,object>>(body);}catch{result=new Dictionary<string,object>();}result["_http"]=status;return result;}finally{Active=null;}
  }
 }
 public static void Cancel(){Process p=Active;if(p!=null){try{p.Kill();}catch{}}}
}

public class Shell {
 public Window Window;Workspace data;Account account;string dir,workspaceFile,secretFile;Track selected;bool busy,verifiedAccount;MediaPlayer player=new MediaPlayer();string authUrl,authState,verifier;DateTime authStarted;TcpListener listener;bool authPending;int authClaimed;object accountLock=new object();
 T Get<T>(string name)where T:class{return Window.FindName(name)as T;}
 TextBox Box(string name){return Get<TextBox>(name);}string Text(string name){return Box(name).Text.Trim();}
 void Click(string name,Action action){Get<Button>(name).Click+=delegate{try{action();}catch(Exception e){Notify(e.Message);}};}
 public Shell():this(null){}
 public Shell(string isolatedDirectory){dir=isolatedDirectory??Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"Soundcloud Desktop Native");Directory.CreateDirectory(dir);workspaceFile=Path.Combine(dir,"workspace.json");secretFile=Path.Combine(dir,"account.secure");data=File.Exists(workspaceFile)?Deserialize<Workspace>(File.ReadAllText(workspaceFile)):new Workspace();Validate(data);account=File.Exists(secretFile)?Deserialize<Account>(Encoding.UTF8.GetString(ProtectedData.Unprotect(File.ReadAllBytes(secretFile),null,DataProtectionScope.CurrentUser))):new Account();using(Stream s=typeof(Shell).Assembly.GetManifestResourceStream("App.xaml"))Window=(Window)XamlReader.Load(s);Window.Icon=BitmapFrame.Create(new Uri(Path.Combine(Transport.Root,"icon.ico")));Wire();Refresh();
 Window.AllowDrop=true;Window.DragOver+=delegate(object s,DragEventArgs e){e.Effects=e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;e.Handled=true;};Window.Drop+=delegate(object s,DragEventArgs e){if(busy)return;string[] files=e.Data.GetData(DataFormats.FileDrop)as string[];if(files!=null){Import(files);if(files.Length>0)SelectFile(files[0]);}};Window.Closing+=delegate(object s,System.ComponentModel.CancelEventArgs e){if(busy){e.Cancel=true;Window.WindowState=WindowState.Minimized;Notify("An operation is still running. Cancel the transfer before closing.");}else{listenerStop();player.Close();}};
 player.MediaFailed+=delegate{Notify("The installed Windows codecs cannot preview this file. It can still be uploaded.");};
 Page("Account");Window.Loaded+=delegate{if(!String.IsNullOrEmpty(account.Access)){Notify("Verifying your SoundCloud account…");Work(delegate{VerifyAccount();},delegate{Refresh();Page("Upload");Notify("Verified SoundCloud account: "+account.User);});}};
 }
 public void Notify(string text){Get<TextBlock>("Info").Text=text;Get<Border>("InfoBar").Visibility=System.Windows.Visibility.Visible;}
 void Page(string page){foreach(string s in new[]{"Upload","Library","Releases","Promotion","Studio","Amplify","Insights","Monetization","Account","Settings"}){Get<StackPanel>(s+"Page").Visibility=s==page?System.Windows.Visibility.Visible:System.Windows.Visibility.Collapsed;Get<Button>("Nav"+s).Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString(s==page?"#38332F":"#202124"));}}
 void Wire(){foreach(string name in new[]{"Upload","Library","Releases","Promotion","Studio","Amplify","Insights","Monetization","Account","Settings"}){string captured=name;Click("Nav"+name,delegate{Page(captured);});}Page("Upload");
 Click("OpenStudio",delegate{Open("https://artists.soundcloud.com/");});Click("OpenOnlineTracks",delegate{Open("https://soundcloud.com/you/tracks");});Click("OpenAmplifyStudio",delegate{Open("https://artists.soundcloud.com/");});Click("AmplifyGuide",delegate{Open("https://help.soundcloud.com/hc/en-us/articles/16680415453979-Amplify-tracks-to-reach-100-listeners");});Click("DetailedInsights",delegate{Open("https://soundcloud.com/you/insights");});Click("OpenMonetization",delegate{Open("https://artists.soundcloud.com/monetization/soundcloud");});Click("OpenEarnings",delegate{Open("https://artists.soundcloud.com/earnings");});Click("OpenPayouts",delegate{Open("https://artists.soundcloud.com/earnings/payouts");});Click("MonetizationGuide",delegate{Open("https://help.soundcloud.com/hc/en-us/articles/4406233941787-Start-Monetizing-with-SoundCloud-for-Artists");});Click("PayoutGuide",delegate{Open("https://help.soundcloud.com/hc/en-us/articles/360051802713-Getting-Paid-by-SoundCloud-for-Artists");});
 Click("RefreshInsights",delegate{long plays=0,likes=0;int count=0;Work(delegate{VerifyAccount();string next="https://api.soundcloud.com/me/tracks?linked_partitioning=true&limit=200";int pages=0;while(!String.IsNullOrEmpty(next)&&pages++<50){var result=Transport.Request(next,account.Access,null,null,true);var list=result.ContainsKey("collection")?result["collection"]as System.Collections.IEnumerable:null;if(list!=null)foreach(object item in list){var t=item as Dictionary<string,object>;if(t==null)continue;count++;if(t.ContainsKey("playback_count")&&t["playback_count"]!=null)plays+=Convert.ToInt64(t["playback_count"]);if(t.ContainsKey("likes_count")&&t["likes_count"]!=null)likes+=Convert.ToInt64(t["likes_count"]);else if(t.ContainsKey("favoritings_count")&&t["favoritings_count"]!=null)likes+=Convert.ToInt64(t["favoritings_count"]);}next=Value(result,"next_href");}if(!String.IsNullOrEmpty(next))throw new Exception("Catalog exceeds the 10,000-track limit. Open detailed Insights for complete reporting.");},delegate{Refresh();Get<TextBlock>("InsightAccount").Text=account.User+" · Verified SoundCloud account";Get<TextBlock>("InsightTracks").Text=count.ToString("N0");Get<TextBlock>("InsightPlays").Text=plays.ToString("N0");Get<TextBlock>("InsightLikes").Text=likes.ToString("N0");Get<TextBlock>("InsightUpdated").Text="Updated "+DateTime.Now.ToString("g");});});
 Click("ChooseAudio",delegate{Choose(false);});Click("ImportLibrary",delegate{Choose(true);});Click("UseTrack",delegate{Track t=Get<ListBox>("TrackList").SelectedItem as Track;if(t!=null)SelectFile(t.File);});Click("RevealTrack",delegate{Track t=Get<ListBox>("TrackList").SelectedItem as Track;if(t!=null&&File.Exists(t.File))Process.Start("explorer.exe","/select,\""+t.File+"\"");});
 Click("PreviewTrack",delegate{Track t=Get<ListBox>("TrackList").SelectedItem as Track;if(t!=null&&RequestHardwareConsent("audio-output","Preview your selected music through this PC's speakers or headphones.")){player.Open(new Uri(t.File));player.Play();Get<TextBlock>("PlayerLabel").Text="♫  "+t.Title;}});Click("PauseTrack",delegate{player.Pause();});Click("RemoveTrack",delegate{Track t=Get<ListBox>("TrackList").SelectedItem as Track;if(t!=null&&MessageBox.Show("Remove this entry from the library? Original audio is preserved.","Remove track",MessageBoxButton.YesNo)==MessageBoxResult.Yes){data.Tracks.Remove(t);Save();Refresh();}});
 Click("ResetHardware",delegate{string file=Path.Combine(dir,"hardware-consent.json");if(File.Exists(file))File.Delete(file);player.Stop();Get<TextBlock>("HardwareState").Text="Speaker and headphone playback: ask before use.";Notify("Playback consent reset. You will be asked before the next preview.");});
 Click("ChooseArt",delegate{if(selected==null){Notify("Choose an audio file first.");return;}OpenFileDialog d=new OpenFileDialog{Filter="Artwork|*.png;*.jpg;*.jpeg"};if(d.ShowDialog(Window)==true){if(new FileInfo(d.FileName).Length>10*1024*1024)throw new Exception("Choose artwork under 10 MB.");string folder=Path.Combine(dir,"artwork");Directory.CreateDirectory(folder);selected.Art=Path.Combine(folder,Guid.NewGuid()+Path.GetExtension(d.FileName));File.Copy(d.FileName,selected.Art);Save();ShowArt();}});
 Click("SaveCredentials",delegate{if(busy||authPending)throw new Exception("Finish the current connection attempt first.");if(Text("ClientId")==""||Get<PasswordBox>("ClientSecret").Password=="")throw new Exception("Enter the Client ID and secret from your registered app.");verifiedAccount=false;account=new Account{ClientId=Text("ClientId"),Secret=Get<PasswordBox>("ClientSecret").Password};SaveAccount();Get<PasswordBox>("ClientSecret").Clear();Refresh();Notify("Credentials encrypted and saved for your Windows account.");});
 Click("ConnectAccount",StartAuth);Click("RegistrationGuide",delegate{Open("https://developers.soundcloud.com/docs/api/register-app");});Click("CopyAuthLink",delegate{if(authUrl==null)throw new Exception("Click Connect with SoundCloud first.");Clipboard.SetText(authUrl);Notify("Authorization link copied. Use a browser you trust.");});Click("FinishCallback",delegate{CompleteCallback(Text("CallbackAddress"));});
 Click("SyncAccount",delegate{Work(delegate{VerifyAccount();},delegate{Refresh();Page("Upload");Notify("Verified SoundCloud account: "+account.User+".");});});
 Click("DisconnectAccount",delegate{if(busy||authPending)throw new Exception("Finish the active operation first.");verifiedAccount=false;account.Access=null;account.Refresh=null;account.User=null;SaveAccount();Refresh();Notify("Local account tokens removed. Revoke app access in SoundCloud to revoke it remotely.");});Click("OpenInsights",delegate{Open("https://soundcloud.com/you/insights");});
 Click("UploadButton",Upload);Click("CancelUpload",delegate{Transport.Cancel();});
 Click("SaveRelease",delegate{if(Text("ReleaseTitle")=="")throw new Exception("Enter a release title.");Release r=Get<ListBox>("ReleaseList").SelectedItem as Release;if(r==null){r=new Release();data.Releases.Add(r);}r.Title=Text("ReleaseTitle");r.Date=Get<DatePicker>("ReleaseDate").SelectedDate.HasValue?Get<DatePicker>("ReleaseDate").SelectedDate.Value.ToString("yyyy-MM-dd"):"TBD";r.Notes=Text("ReleaseNotes");r.Master=Get<CheckBox>("MasterDone").IsChecked==true;r.Artwork=Get<CheckBox>("ArtworkDone").IsChecked==true;r.Metadata=Get<CheckBox>("MetadataDone").IsChecked==true;r.Published=Get<CheckBox>("PublishedDone").IsChecked==true;Save();Refresh();Notify("Release plan saved.");});
 Get<ListBox>("ReleaseList").SelectionChanged+=delegate{Release r=Get<ListBox>("ReleaseList").SelectedItem as Release;if(r==null)return;Box("ReleaseTitle").Text=r.Title;Box("ReleaseNotes").Text=r.Notes;DateTime dt;Get<DatePicker>("ReleaseDate").SelectedDate=DateTime.TryParse(r.Date,out dt)?(DateTime?)dt:null;Get<CheckBox>("MasterDone").IsChecked=r.Master;Get<CheckBox>("ArtworkDone").IsChecked=r.Artwork;Get<CheckBox>("MetadataDone").IsChecked=r.Metadata;Get<CheckBox>("PublishedDone").IsChecked=r.Published;};
 Click("SaveCampaign",delegate{if(Text("CampaignTitle")=="")throw new Exception("Enter a campaign title.");Campaign c=Get<ListBox>("CampaignList").SelectedItem as Campaign;if(c==null){c=new Campaign();data.Campaigns.Add(c);}c.Title=Text("CampaignTitle");c.Contact=Text("CampaignContact");c.Text=Text("CampaignText");Save();Refresh();Notify("Campaign saved.");});Click("CopyCampaign",delegate{Clipboard.SetText(Text("CampaignText"));Notify("Campaign text copied.");});Get<ListBox>("CampaignList").SelectionChanged+=delegate{Campaign c=Get<ListBox>("CampaignList").SelectedItem as Campaign;if(c!=null){Box("CampaignTitle").Text=c.Title;Box("CampaignContact").Text=c.Contact;Box("CampaignText").Text=c.Text;}};
 Click("ExportData",delegate{SaveFileDialog d=new SaveFileDialog{Filter="Workspace JSON|*.json",FileName="Soundcloud-Desktop-native-backup.json"};if(d.ShowDialog(Window)==true){File.WriteAllText(d.FileName,Serialize(data));Notify("Workspace backup exported. Audio files and credentials are not included.");}});
 Click("ImportData",delegate{if(busy)throw new Exception("Finish the active operation first.");OpenFileDialog d=new OpenFileDialog{Filter="Workspace JSON|*.json"};if(d.ShowDialog(Window)==true){Workspace next=Deserialize<Workspace>(File.ReadAllText(d.FileName));Validate(next);if(MessageBox.Show("Replace the workspace? A copy of the current metadata will be preserved.","Restore backup",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;File.WriteAllText(workspaceFile+".before-restore-"+DateTime.Now.Ticks,Serialize(data));data=next;selected=null;Save();Refresh();Notify("Workspace restored.");}});
 Click("CheckNetwork",delegate{Work(delegate{var p=Transport.Request("https://api.soundcloud.com/me",null,null,null,false);if(Convert.ToInt32(p["_http"])!=401)throw new Exception("Unexpected API response. Try again later.");},delegate{Notify("Verified HTTPS connection to SoundCloud. Certificate validation passed; the API correctly requires account authorization.");});});
 }
 public bool RequestHardwareConsent(string feature,string purpose){if(feature!="audio-output")return false;string file=Path.Combine(dir,"hardware-consent.json");if(File.Exists(file)){bool allowed=Deserialize<bool>(File.ReadAllText(file));if(!allowed)Notify("Audio playback is denied. Reset playback consent in Settings to change it.");return allowed;}
  Window prompt=new Window{Title="Hardware permission",Width=450,SizeToContent=SizeToContent.Height,ResizeMode=ResizeMode.NoResize,Owner=Window,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=Window.Background,Foreground=Window.Foreground,FontFamily=Window.FontFamily,ShowInTaskbar=false};prompt.Resources=Window.Resources;StackPanel content=new StackPanel{Margin=new Thickness(25)};content.Children.Add(new TextBlock{Text="Allow audio playback?",FontSize=23,FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,0,0,16)});content.Children.Add(new TextBlock{Text=purpose,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,15)});CheckBox remember=new CheckBox{Content="Remember my choice on this PC",Margin=new Thickness(0,0,0,20)};content.Children.Add(remember);StackPanel buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};Button deny=new Button{Content="Deny",MinWidth=95};Button allow=new Button{Content="Allow",MinWidth=95,Background=new SolidColorBrush(Color.FromRgb(232,85,27))};bool granted=false;deny.Click+=delegate{prompt.DialogResult=false;};allow.Click+=delegate{granted=true;prompt.DialogResult=true;};buttons.Children.Add(deny);buttons.Children.Add(allow);content.Children.Add(buttons);prompt.Content=content;prompt.ShowDialog();if(remember.IsChecked==true){Atomic(file,Encoding.UTF8.GetBytes(Serialize(granted)));Get<TextBlock>("HardwareState").Text="Speaker and headphone playback: "+(granted?"allowed":"denied")+". Reset below to change.";}return granted;
 }
 void Choose(bool multi){if(busy)throw new Exception("Wait for the current operation to finish.");OpenFileDialog d=new OpenFileDialog{Multiselect=multi,Filter="Audio files|*.wav;*.mp3;*.flac;*.aiff;*.aif;*.ogg;*.m4a;*.aac;*.wma;*.mp2;*.amr"};if(d.ShowDialog(Window)==true){Import(d.FileNames);if(!multi)SelectFile(d.FileName);}}
 void Import(string[] paths){int count=0;foreach(string file in paths){if(!File.Exists(file)||!new[]{".wav",".mp3",".flac",".aiff",".aif",".ogg",".m4a",".aac",".wma",".mp2",".amr"}.Contains(Path.GetExtension(file).ToLowerInvariant()))continue;if(data.Tracks.Any(t=>String.Equals(t.File,file,StringComparison.OrdinalIgnoreCase)))continue;data.Tracks.Add(new Track{Id=Guid.NewGuid().ToString(),File=file,Title=Path.GetFileNameWithoutExtension(file)});count++;}Save();Refresh();Notify(count+" audio file(s) added. Originals are preserved.");}
 void SelectFile(string file){selected=data.Tracks.FirstOrDefault(t=>String.Equals(t.File,file,StringComparison.OrdinalIgnoreCase));if(selected==null)return;Box("TrackTitle").Text=selected.Title;Get<TextBlock>("AudioName").Text=Path.GetFileName(file)+"  ·  "+(new FileInfo(file).Length/1048576.0).ToString("0.0")+" MB";Get<ComboBox>("VisibilityChoice").SelectedIndex=0;ShowArt();Page("Upload");}
 void ShowArt(){if(selected!=null&&!String.IsNullOrEmpty(selected.Art)&&File.Exists(selected.Art)){BitmapImage image=new BitmapImage();image.BeginInit();image.CacheOption=BitmapCacheOption.OnLoad;image.UriSource=new Uri(selected.Art);image.EndInit();Get<Image>("ArtworkImage").Source=image;Get<Image>("ArtworkImage").Visibility=System.Windows.Visibility.Visible;Get<TextBlock>("ArtworkName").Text="Artwork attached";}else{Get<Image>("ArtworkImage").Visibility=System.Windows.Visibility.Collapsed;Get<TextBlock>("ArtworkName").Text="Optional · JPG or PNG · up to 10 MB";}}
 void Refresh(){Get<TextBlock>("StudioIdentity").Text=verifiedAccount?account.User+" - Verified SoundCloud account":"Connect and verify your artist account to begin.";Get<ListBox>("TrackList").ItemsSource=null;Get<ListBox>("TrackList").ItemsSource=data.Tracks;Get<ListBox>("ReleaseList").ItemsSource=null;Get<ListBox>("ReleaseList").ItemsSource=data.Releases;Get<ListBox>("CampaignList").ItemsSource=null;Get<ListBox>("CampaignList").ItemsSource=data.Campaigns;Box("ClientId").Text=account.ClientId??"";Get<TextBlock>("AccountBadge").Text=!verifiedAccount?"Not connected":"Connected · "+account.User;Get<TextBlock>("ConnectionState").Text=String.IsNullOrEmpty(account.Access)?(String.IsNullOrEmpty(account.ClientId)?"No credentials saved.":"Credentials saved. Connect your account."):"Connected as "+account.User;if(!String.IsNullOrEmpty(account.User)&&Box("Artist").Text=="")Box("Artist").Text=account.User;}
 void Work(Action action,Action done){if(busy)throw new Exception("An operation is already running.");busy=true;Get<Button>("UploadButton").IsEnabled=false;ThreadPool.QueueUserWorkItem(delegate{Exception error=null;try{action();}catch(Exception e){error=e;}Window.Dispatcher.BeginInvoke(new Action(delegate{busy=false;Get<Button>("UploadButton").IsEnabled=true;Get<Button>("CancelUpload").Visibility=System.Windows.Visibility.Collapsed;Get<ProgressBar>("TransferProgress").IsIndeterminate=false;if(error!=null)Notify(error.Message);else if(done!=null)done();}));});}
 void Upload(){if(selected==null)throw new Exception("Choose your audio file first.");if(!verifiedAccount){Page("Account");Notify("Connect and verify your artist account before uploading.");return;}if(Text("TrackTitle")=="")throw new Exception("Enter a track title.");Track track=selected;string sharing=Get<ComboBox>("VisibilityChoice").SelectedIndex==1?"public":"private";if(track.Upload!=null&&MessageBox.Show("This file was uploaded before. Upload a separate copy?","Duplicate upload",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;
 var fields=new Dictionary<string,string>{{"title",Text("TrackTitle")},{"artist",Text("Artist")},{"genre",Text("Genre")},{"description",Text("Description")},{"sharing",sharing}};track.Title=fields["title"];Save();Get<ProgressBar>("TransferProgress").Value=0;Get<ProgressBar>("TransferProgress").IsIndeterminate=true;Get<Button>("CancelUpload").Visibility=System.Windows.Visibility.Visible;Get<TextBlock>("UploadHint").Text="Connecting securely to SoundCloud…";Transport.Progress=delegate(int p){Window.Dispatcher.BeginInvoke(new Action(delegate{Get<ProgressBar>("TransferProgress").IsIndeterminate=false;Get<ProgressBar>("TransferProgress").Value=p;Get<TextBlock>("UploadHint").Text=p+"% transferred · Keep the app running";}));};Dictionary<string,object> result=null;
 Work(delegate{VerifyAccount();result=Transport.Request("https://api.soundcloud.com/tracks",account.Access,fields,track.File,true,track.Art);if(!result.ContainsKey("id")&&!result.ContainsKey("urn"))throw new Exception("No track identifier returned. Check your catalog before retrying.");},delegate{track.Link=Value(result,"permalink_url");track.Upload=sharing+" · "+DateTime.Now.ToString("g");Save();Refresh();Get<ProgressBar>("TransferProgress").Value=100;Get<TextBlock>("UploadHint").Text="Upload accepted. SoundCloud may still be processing the audio.";Notify("Uploaded "+track.Title+" as "+sharing+". "+track.Link);});
 }
 void StartAuth(){if(busy||authPending)throw new Exception("An operation is already running.");if(String.IsNullOrEmpty(account.ClientId)||String.IsNullOrEmpty(account.Secret))throw new Exception("Save your registered app credentials first.");verifier=Random();authState=Random();authStarted=DateTime.UtcNow;authClaimed=0;string challenge;using(var sha=SHA256.Create())challenge=B64(sha.ComputeHash(Encoding.ASCII.GetBytes(verifier)));authUrl="https://secure.soundcloud.com/authorize?client_id="+Uri.EscapeDataString(account.ClientId)+"&redirect_uri="+Uri.EscapeDataString("http://127.0.0.1:49832/callback")+"&response_type=code&code_challenge_method=S256&code_challenge="+challenge+"&state="+authState;listener=new TcpListener(IPAddress.Loopback,49832);listener.Start();authPending=true;TcpListener active=listener;
 ThreadPool.QueueUserWorkItem(delegate{while(authPending){try{if(DateTime.UtcNow-authStarted>TimeSpan.FromMinutes(5)){Window.Dispatcher.BeginInvoke(new Action(delegate{listenerStop();Notify("Authorization expired. Connect again to start a new request.");}));break;}if(!active.Pending()){Thread.Sleep(150);continue;}using(TcpClient client=active.AcceptTcpClient()){client.ReceiveTimeout=5000;using(NetworkStream stream=client.GetStream()){StreamReader reader=new StreamReader(stream);string line=reader.ReadLine();if(line==null||line.Length>8192)continue;string[] parts=line.Split(' ');if(parts.Length<2)continue;string callback="http://127.0.0.1:49832"+parts[1];string message="Return to Soundcloud Desktop to finish connecting.";byte[] body=Encoding.UTF8.GetBytes(message);byte[] header=Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: "+body.Length+"\r\nConnection: close\r\n\r\n");stream.Write(header,0,header.Length);stream.Write(body,0,body.Length);Window.Dispatcher.BeginInvoke(new Action(delegate{try{CompleteCallback(callback);}catch(Exception e){Notify(e.Message);}}));}}}catch{if(!authPending)break;}}});Open(authUrl);Notify("Approve access in your browser. You can also copy the authorization link to another device.");}
 void CompleteCallback(string address){if(!authPending||DateTime.UtcNow-authStarted>TimeSpan.FromMinutes(5))throw new Exception("Start a new connection attempt first.");Uri u;if(!Uri.TryCreate(address,UriKind.Absolute,out u)||u.Host!="127.0.0.1"||u.Port!=49832||u.AbsolutePath!="/callback")throw new Exception("Paste the full redirect address from the authorization browser.");var q=HttpUtility.ParseQueryString(u.Query);if(q["state"]!=authState)throw new Exception("Authorization state did not match. Use the current connection attempt.");if(String.IsNullOrEmpty(q["code"]))throw new Exception("Authorization was not approved.");if(Interlocked.Exchange(ref authClaimed,1)!=0)return;string code=q["code"];listenerStop();Box("CallbackAddress").Clear();Work(delegate{Exchange(new Dictionary<string,string>{{"grant_type","authorization_code"},{"code",code},{"code_verifier",verifier},{"redirect_uri","http://127.0.0.1:49832/callback"}});VerifyAccount();},delegate{Refresh();Page("Upload");Notify("Connected as "+account.User+". You can upload your music now.");});}
 void listenerStop(){authPending=false;if(listener!=null){listener.Stop();listener=null;}}
 void VerifyAccount(){verifiedAccount=false;EnsureToken();var profile=Transport.Request("https://api.soundcloud.com/me",account.Access,null,null,true);if(!profile.ContainsKey("id")&&!profile.ContainsKey("urn"))throw new Exception("SoundCloud did not return a verified account ID. Reconnect before uploading.");account.User=Value(profile,"username");SaveAccount();verifiedAccount=true;}
 void EnsureToken(){lock(accountLock){if(String.IsNullOrEmpty(account.Access))throw new Exception("Connect your account first.");if(DateTime.UtcNow.Ticks>account.Expires-TimeSpan.FromMinutes(1).Ticks)Exchange(new Dictionary<string,string>{{"grant_type","refresh_token"},{"refresh_token",account.Refresh}});}}
 void Exchange(Dictionary<string,string> fields){fields["client_id"]=account.ClientId;fields["client_secret"]=account.Secret;var result=Transport.Request("https://secure.soundcloud.com/oauth/token",null,fields,null,true);string access=Value(result,"access_token"),refresh=Value(result,"refresh_token");if(access==""||refresh=="")throw new Exception("SoundCloud did not return complete credentials.");account.Access=access;account.Refresh=refresh;account.Expires=DateTime.UtcNow.AddSeconds(result.ContainsKey("expires_in")?Convert.ToDouble(result["expires_in"]):3600).Ticks;SaveAccount();}
 void SaveAccount(){byte[] bytes=ProtectedData.Protect(Encoding.UTF8.GetBytes(Serialize(account)),null,DataProtectionScope.CurrentUser);Atomic(secretFile,bytes);}
 void Save(){Validate(data);Atomic(workspaceFile,Encoding.UTF8.GetBytes(Serialize(data)));}
 public static void Atomic(string path,byte[] bytes){string temp=path+".tmp";File.WriteAllBytes(temp,bytes);if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}
 public static void Validate(Workspace w){if(w==null||w.Version!=1||w.Tracks==null||w.Releases==null||w.Campaigns==null||w.Tracks.Any(t=>t==null||String.IsNullOrEmpty(t.Id)||String.IsNullOrEmpty(t.File)||t.Title==null)||w.Tracks.Select(t=>t.Id).Distinct().Count()!=w.Tracks.Count||w.Releases.Any(r=>r==null||r.Title==null)||w.Campaigns.Any(c=>c==null||c.Title==null))throw new Exception("The workspace is invalid. The existing saved data has been preserved.");}
 public static string Serialize(object o){return new JavaScriptSerializer{MaxJsonLength=16000000}.Serialize(o);}public static T Deserialize<T>(string s){return new JavaScriptSerializer{MaxJsonLength=16000000}.Deserialize<T>(s);}public static string Value(Dictionary<string,object>d,string k){return d.ContainsKey(k)&&d[k]!=null?Convert.ToString(d[k]):"";}
 static string B64(byte[] b){return Convert.ToBase64String(b).TrimEnd('=').Replace('+','-').Replace('/','_');}static string Random(){byte[] b=new byte[32];using(var r=RandomNumberGenerator.Create())r.GetBytes(b);return B64(b);}static void Open(string url){Process.Start(new ProcessStartInfo(url){UseShellExecute=true});}
}
public static class SelfTest {
 public static void Run(){string temp=Path.Combine(Path.GetTempPath(),"scd-native-test-"+Guid.NewGuid());Directory.CreateDirectory(temp);Workspace w=new Workspace();w.Tracks.Add(new Track{Id="1",Title="Native test",File=Path.Combine(temp,"track.wav")});w.Releases.Add(new Release{Title="Test release",Master=true});Shell.Validate(w);string file=Path.Combine(temp,"workspace.json");Shell.Atomic(file,Encoding.UTF8.GetBytes(Shell.Serialize(w)));w.Campaigns.Add(new Campaign{Title="Test campaign",Text="Caption"});Shell.Atomic(file,Encoding.UTF8.GetBytes(Shell.Serialize(w)));var read=Shell.Deserialize<Workspace>(File.ReadAllText(file));if(read.Tracks.Count!=1||!read.Releases[0].Master||read.Campaigns.Count!=1)throw new Exception("Persistence test failed.");byte[] input=Encoding.UTF8.GetBytes("test-only-secret");byte[] encrypted=ProtectedData.Protect(input,null,DataProtectionScope.CurrentUser);if(!input.SequenceEqual(ProtectedData.Unprotect(encrypted,null,DataProtectionScope.CurrentUser)))throw new Exception("Credential test failed.");using(Stream s=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("App.xaml")){Window win=(Window)XamlReader.Load(s);if(win.FindName("UploadButton")==null)throw new Exception("UI test failed.");}File.WriteAllText(Path.Combine(Transport.Root,"self-test-result.txt"),"PASS: native UI loads; metadata save/reload; credential encryption; transport SHA-256 validation. "+DateTime.UtcNow.ToString("o"));}
}
