using System;using System.IO;using System.Reflection;using System.Linq;using System.Text;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Threading;using System.Windows.Media;using System.Windows.Media.Imaging;
public static class Tests {
 static void Click(Shell s,string name){((Button)s.Window.FindName(name)).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));}
 static void Text(Shell s,string name,string text){((TextBox)s.Window.FindName(name)).Text=text;}
 static bool recoveryRan;
 static void Check(bool b,string error){if(!recoveryRan){recoveryRan=true;PersistenceRecovery();}if(!b)throw new Exception(error);}
 static void PersistenceRecovery(){string dir=Path.Combine(Path.GetTempPath(),"scd-native-recovery-"+Guid.NewGuid());Directory.CreateDirectory(dir);string workspace=Path.Combine(dir,"workspace.json");File.WriteAllText(workspace,"{not valid json");Shell recovered=new Shell(dir);Check(File.Exists(workspace),"Recovery should create a fresh workspace");Check(Directory.GetFiles(dir,"workspace.json.corrupt-*").Length==1,"Corrupt workspace must be quarantined");recovered.Window.Close();string a=Path.Combine(dir,"a.bin");byte[] one=Encoding.UTF8.GetBytes("one"),two=Encoding.UTF8.GetBytes("two");Parallel.For(0,20,i=>Shell.Atomic(a,(i%2==0)?one:two));byte[] result=File.ReadAllBytes(a);Check(result.SequenceEqual(one)||result.SequenceEqual(two),"Atomic writes must not interleave");}
 static void Pump(){DispatcherFrame frame=new DispatcherFrame();Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background,new Action(delegate{frame.Continue=false;}));Dispatcher.PushFrame(frame);}
 static void Screenshot(Shell s,string file){s.Window.UpdateLayout();RenderTargetBitmap bmp=new RenderTargetBitmap((int)s.Window.ActualWidth,(int)s.Window.ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(s.Window);PngBitmapEncoder png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(bmp));using(var f=File.Create(file))png.Save(f);}
 [STAThread] public static int Main(){try{string dir=Path.Combine(Path.GetTempPath(),"scd-native-ui-"+Guid.NewGuid());Directory.CreateDirectory(dir);Application app=new Application();Shell s=new Shell(dir);s.Window.Show();Pump();Check(((StackPanel)s.Window.FindName("AccountPage")).Visibility==Visibility.Visible,"Account setup must be first");Check(((Grid)s.Window.FindName("LoginCover")).IsVisible,"Login cover visible");Check(!((Grid)s.Window.FindName("WorkspaceShell")).IsVisible,"Workspace hidden before verification");Click(s,"NavReleases");Check(((StackPanel)s.Window.FindName("AccountPage")).IsVisible,"Navigation cannot bypass sign-in");((Expander)s.Window.FindName("DeveloperSetup")).IsExpanded=false;Screenshot(s,Path.Combine(Transport.Root,"native-login.png"));s.Window.Width=900;s.Window.Height=680;Pump();Screenshot(s,Path.Combine(Transport.Root,"native-login-small.png"));s.Notify("Sign-in could not be completed. Try again.");Check(((TextBlock)s.Window.FindName("LoginStatus")).Text.Contains("Try again"),"Login errors visible on cover");string file=Path.Combine(dir,"master.wav");File.WriteAllBytes(file,new byte[100]);typeof(Shell).GetMethod("Import",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(s,new object[]{new[]{file}});typeof(Shell).GetMethod("SelectFile",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(s,new object[]{file});Text(s,"TrackTitle","Night drive");Screenshot(s,Path.Combine(Transport.Root,"native-upload.png"));Click(s,"UploadButton");Check(((StackPanel)s.Window.FindName("AccountPage")).Visibility==Visibility.Visible,"Unverified upload must be blocked");
 typeof(Shell).GetField("verifiedAccount",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(s,true);typeof(Shell).GetMethod("Refresh",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(s,null);Click(s,"NavUpload");Pump();Check(!((Grid)s.Window.FindName("LoginCover")).IsVisible&&((Grid)s.Window.FindName("WorkspaceShell")).IsVisible,"Verified account opens workspace");Screenshot(s,Path.Combine(Transport.Root,"native-upload.png"));
 Click(s,"NavReleases");Text(s,"ReleaseTitle","Night drive EP");((CheckBox)s.Window.FindName("MasterDone")).IsChecked=true;Click(s,"SaveRelease");Click(s,"NavPromotion");Text(s,"CampaignTitle","Announcement");Text(s,"CampaignText","New music soon");Click(s,"SaveCampaign");Click(s,"CopyCampaign");Check(Clipboard.GetText()=="New music soon","Campaign clipboard");
 DispatcherTimer timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(100)};timer.Tick+=delegate{foreach(Window w in app.Windows){if(w.Title=="Hardware permission"){StackPanel panel=(StackPanel)w.Content;((CheckBox)panel.Children[2]).IsChecked=true;StackPanel buttons=(StackPanel)panel.Children[3];((Button)buttons.Children[0]).RaiseEvent(new RoutedEventArgs(Button.ClickEvent));timer.Stop();break;}}};timer.Start();Check(!s.RequestHardwareConsent("audio-output","Test playback purpose"),"Deny must prevent playback");Check(!s.RequestHardwareConsent("audio-output","Second request"),"Remember deny");Check(!s.RequestHardwareConsent("microphone","Unused feature"),"Unimplemented hardware stays denied");Click(s,"ResetHardware");Check(!File.Exists(Path.Combine(dir,"hardware-consent.json")),"Permission reset");
 Workspace state=Shell.Deserialize<Workspace>(File.ReadAllText(Path.Combine(dir,"workspace.json")));Check(state.Tracks.Count==1&&state.Releases[0].Master&&state.Campaigns.Count==1,"Workspace saves");Click(s,"DisconnectAccount");Pump();Check(((Grid)s.Window.FindName("LoginCover")).IsVisible&&!((Grid)s.Window.FindName("WorkspaceShell")).IsVisible,"Sign-out restores cover");s.Window.Close();Shell second=new Shell(dir);second.Window.Show();Pump();Check(((ListBox)second.Window.FindName("TrackList")).Items.Count==1,"Restart persistence");second.Window.Close();File.WriteAllText(Path.Combine(Transport.Root,"ui-test-result.txt"),"PASS: login cover, navigation gating, verified workspace transition, sign-out cover, visible login errors, minimum-window layout, required account setup, upload blocked without verified account, library import, release checklist, campaign clipboard, persistence, hardware deny/remember/reset, microphone denied.");return 0;}catch(Exception e){File.WriteAllText(Path.Combine(Transport.Root,"ui-test-result.txt"),e.ToString());return 1;}}
}
