const $=s=>document.querySelector(s), api=window.studio;
let state,page='overview',query='',filter='All',current=null,connection={connected:false},editing=null,uploading=false,lastUploaded=null;
const audio=$('#audio');audio.volume=.7;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={overview:'\uE80F',upload:'\uE898',library:'\uE8F1',releases:'\uE787',promotion:'\uE789',soundcloud:'\uE753',settings:'\uE713'};
const titles={overview:'Overview',upload:'Upload music',library:'Music library',releases:'Releases',promotion:'Promotion',soundcloud:'SoundCloud',settings:'Settings'};
const date=s=>s?new Date(s+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'No date set';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const uid=()=>crypto.randomUUID();
function notice(s){$('#notice').textContent=s;$('#notice').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').hidden=true,8000);}
async function safely(fn){try{return await fn();}catch(e){notice(e.message.replace(/^Error invoking remote method '[^']+': Error: /,''));}}
async function save(){try{state=await api.save(state);}catch(e){state=await api.read();render();throw e;}render();if(current){const t=state.tracks.find(t=>t.id===current);if(t){$('#now-title').textContent=t.title;$('#now-sub').textContent=`${t.format} · ${t.status}`;}}}
function head(title,sub,buttons=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${buttons}</div></div>`;}
function empty(icon,title,sub,button=''){return `<div class="empty"><div class="empty-icon">${icon}</div><h3>${title}</h3><p>${sub}</p>${button}</div>`;}
function btn(action,text,primary=false,id=''){return `<button data-action="${action}" data-id="${esc(id)}" class="${primary?'primary':''}">${text}</button>`;}
function wave(){return `<div class="hero-art" aria-hidden="true">${[18,32,49,28,61,87,67,105,129,96,76,119,147,110,85,62,96,74,47,66,40,25,34].map(h=>`<i style="--h:${h}px"></i>`).join('')}</div>`;}
function render(){
 $('#studio-name').textContent=state.profile.name;$('.avatar').textContent=state.profile.name[0]?.toUpperCase()||'S';
 document.body.classList.toggle('light',state.profile.theme==='light'||state.profile.theme==='system'&&matchMedia('(prefers-color-scheme:light)').matches);
 $('#nav').innerHTML=Object.entries(titles).filter(([k])=>k!=='settings').map(([k,v],i)=>`${i===5?'<div class="nav-label">CONNECTED SERVICES</div>':''}<button data-page="${k}" class="${page===k?'active':''}" ${page===k?'aria-current="page"':''}><span class="icon">${icons[k]}</span>${v}</button>`).join('');
 $('#breadcrumb').textContent='Workspace / '+titles[page];$('#today').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});
 $('#view').innerHTML=({overview,upload:uploadPage,library,releases,promotion,soundcloud,settings}[page])();
}
function overview(){const upcoming=[...state.releases].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));const tasks=state.releases.flatMap(r=>r.checks.filter(c=>!c.done).map(c=>({title:c.label,release:r.title}))).slice(0,3);
 return head('Your next release starts here.','Upload your music. Shape your release. Reach your listeners.',btn('upload-page','↑ Upload music',true))+
 `<section class="hero"><div><div class="eyebrow">FROM FIRST DEMO TO RELEASE DAY</div><h2>From your studio.<br>To your SoundCloud.</h2><p>Upload your next track directly to your artist account. Add the details, choose who can listen, and make it yours.</p>${btn('upload-page','↑ Upload a track',true)} <button data-page="library" class="quiet">Open library →</button></div>${wave()}</section>`+
 `<div class="stats">${[['Local tracks',state.tracks.length,'Demos, mixes & masters'],['Planned releases',state.releases.length,'Your release workspace'],['Ready to release',state.tracks.filter(t=>t.status==='Mastered').length,'Tracks marked mastered'],['Promotion tasks',state.campaigns.filter(c=>c.status!=='Done').length,'Still on your list']].map(([l,n,s])=>`<div class="stat"><div class="label">${l}</div><strong>${n.toString().padStart(2,'0')}</strong><small>${s}</small></div>`).join('')}</div>`+
 `<div class="columns"><section><div class="section-head"><h2>On the release radar</h2><button class="link" data-page="releases">View all →</button></div><div class="panel">${upcoming.length?upcoming.slice(0,3).map(r=>`<div class="task-row"><div class="number">♫</div><div><h3>${esc(r.title)}</h3><p>${date(r.date)} · ${r.checks.filter(c=>c.done).length}/${r.checks.length} steps complete</p></div><button data-page="releases" class="quiet">→</button></div>`).join(''):empty('◷','Your next release starts here','Set a date, add artwork, and keep the small details from getting in the way.',btn('new-release','Create your first release'))}</div></section><section><div class="section-head"><h2>${tasks.length?'Next steps':'Set up your workspace'}</h2><span class="tag">${tasks.length?'TO DO':'LET’S BEGIN'}</span></div><div class="panel">${tasks.length?tasks.map((t,i)=>`<div class="task-row"><div class="number">${i+1}</div><div><h3>${esc(t.title)}</h3><p>${esc(t.release)}</p></div></div>`).join(''):[['Bring in your music','Add audio files from your PC','import'],['Map out a release','Artwork, dates, and a checklist','new-release'],['Connect with SoundCloud','Link your artist account','connect-page']].map(([t,s,a],i)=>`<div class="task-row"><div class="number">${i+1}</div><div><h3>${t}</h3><p>${s}</p></div><button class="quiet" data-action="${a}" aria-label="${t}">→</button></div>`).join('')}</div></section></div>`;
}
function library(){const tracks=state.tracks.filter(t=>(filter==='All'||t.status===filter)&&`${t.title} ${t.genre} ${t.notes}`.toLowerCase().includes(query.toLowerCase()));return head('Music library','A home for every version of your sound.',btn('import','＋ Import tracks',true))+`<div class="toolbar"><div class="filters">${['All','Draft','Mixing','Mastered','Released'].map(v=>`<button data-filter="${v}" class="${filter===v?'selected':''}">${v}</button>`).join('')}</div><input class="search" id="search" aria-label="Search tracks" placeholder="Search tracks, genres, notes" value="${esc(query)}"></div><div class="panel">${tracks.length?`<table><thead><tr><th>TRACK</th><th>FORMAT</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>${tracks.map(t=>`<tr><td><div class="track-title"><button class="track-play" data-action="play-track" data-id="${t.id}" aria-label="Play ${esc(t.title)}">▶</button><div><strong>${esc(t.title)}</strong><small>${esc(t.genre||'No genre')} · ${(t.size/1048576).toFixed(1)} MB</small></div></div></td><td>${esc(t.format)}</td><td><span class="tag ${t.status==='Mastered'?'green':''}">${t.status}</span></td><td><div class="row-actions">${btn('upload-track','Upload',false,t.id)}${btn('edit-track','Edit',false,t.id)}${btn('reveal','↗',false,t.id)}</div></td></tr>`).join('')}</tbody></table>`:empty('♫',state.tracks.length?'No matching tracks':'Give your music a home',state.tracks.length?'Try another search or status filter.':'Import your demos, mixes, and masters. Your original files stay where they are.',btn('import','Choose audio files',true))}</div><div class="drop-zone">＋ Drop audio files anywhere in the workspace to import · MP3, WAV, FLAC, M4A, OGG, AAC, AIFF</div><p class="subtitle-note">Playback support depends on the audio codec. Importing does not upload or publish your music.</p>`;}
function releases(){return head('Releases','Turn a finished track into a release you’re proud of.',btn('new-release','＋ New release',true))+ (state.releases.length?`<div class="release-grid">${state.releases.map(r=>{const done=r.checks.filter(c=>c.done).length;return `<article class="release-card"><div class="cover">${r.art?`<img src="studio://art/${r.id}" alt="Artwork for ${esc(r.title)}">`:'♫'}${btn('artwork','Choose artwork',false,r.id)}</div><div class="release-body"><div class="section-head"><span class="tag">${esc(r.type||'Single')}</span><small>${date(r.date)}</small></div><h2>${esc(r.title)}</h2><p>${r.trackId?esc(state.tracks.find(t=>t.id===r.trackId)?.title||'Track removed from library'):'No track linked yet'}</p><div class="progress"><div style="width:${done/r.checks.length*100}%"></div></div><small>${done} of ${r.checks.length} steps complete</small><div class="checklist">${r.checks.map((c,i)=>`<label><input type="checkbox" data-check="${r.id}" data-index="${i}" ${c.done?'checked':''}>${esc(c.label)}</label>`).join('')}</div><div class="card-bottom">${btn('edit-release','Edit details',false,r.id)}${btn('release-copy','Copy release brief',false,r.id)}</div></div></article>`;}).join('')}</div>`:`<div class="panel full-empty">${empty('◷','The next chapter of your sound','Plan a single, EP, or album. Bring the artwork, track, credits, and release tasks together.',btn('new-release','Plan your first release',true))}</div>`)+`<p class="subtitle-note">Dates are for planning. Publishing and scheduling on SoundCloud are managed separately.</p>`;}
function promotion(){return head('Promotion','Give every release a thoughtful introduction.',btn('new-campaign','＋ New campaign',true))+(state.campaigns.length?`<div class="release-grid">${state.campaigns.map(c=>`<article class="panel campaign"><span class="tag ${c.status==='Done'?'green':''}">${c.status}</span><h3>${esc(c.title)}</h3><p>${esc(c.caption||'Add your caption, pitch, or campaign notes.')}</p><div class="meta">${esc(c.channel||'General')} · ${date(c.date)}${c.contact?'<br>'+esc(c.contact):''}</div><div class="card-bottom">${btn('edit-campaign','Edit campaign',false,c.id)}${btn('copy-campaign','Copy text',false,c.id)}</div></article>`).join('')}</div>`:`<div class="panel full-empty">${empty('↗','Good music deserves to be heard','Plan social posts, playlist pitches, and personal outreach. Keep captions and links ready to copy.',btn('new-campaign','Create a campaign',true))}</div>`);}
function soundcloud(){const data=connection.snapshot;return head('Your SoundCloud','Connect your artist account and keep your catalog in view.',btn('open-home','Open SoundCloud ↗'))+`<section class="panel settings-block"><div class="connection"><div class="connection-icon">☁</div><div><h2>${connection.connected?esc(data?.profile?.username||'SoundCloud connected'):'Bring your artist account into the workspace'}</h2><p>${connection.connected?'Account connected · '+(data?.syncedAt?'Last synced '+new Date(data.syncedAt).toLocaleString():'Ready to sync'):'Connect securely using your own registered SoundCloud app.'}</p></div></div><div class="actions" style="margin-top:22px">${connection.connected?btn('sync','↻ Sync catalog',true)+btn('disconnect','Disconnect'):btn('authorize','Connect with SoundCloud',true)}${btn('upload-page','↑ Upload music')}${btn('open-insights','Open Artist Insights ↗')}</div></section>${data?`<div class="stats">${[['Followers',data.profile.followers_count??'—'],['Tracks',data.profile.track_count??data.tracks.length],['Catalog plays',data.tracks.reduce((s,t)=>s+(t.playback_count||0),0)],['Catalog likes',data.tracks.reduce((s,t)=>s+(t.likes_count||t.favoritings_count||0),0)]].map(([s,n])=>`<div class="stat"><div class="label">${s}</div><strong>${Number.isFinite(n)?n.toLocaleString():n}</strong><small>Latest synced snapshot</small></div>`).join('')}</div><div class="panel"><table><thead><tr><th>TRACK</th><th>VISIBILITY</th><th>PLAYS</th><th>LIKES</th></tr></thead><tbody>${data.tracks.map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.sharing)}</td><td>${(t.playback_count||0).toLocaleString()}</td><td>${(t.likes_count||t.favoritings_count||0).toLocaleString()}</td></tr>`).join('')}</tbody></table></div><p class="subtitle-note">Counts reflect tracks returned by the public API. Detailed time-based analytics are available in Artist Insights.</p>`:''}<section class="panel settings-block" style="margin-top:20px"><h2>Connection setup</h2><p>Your Artist Pro plan lets you register an API application. Create an app in SoundCloud, set the redirect address below, then enter its credentials here. Credentials are encrypted for your Windows account and excluded from workspace backups.</p><div class="actions">${btn('open-api','API registration guide ↗')}${btn('copy-redirect','Copy redirect address')}</div><p class="mono" style="margin-top:16px">http://127.0.0.1:49832/callback</p><div class="split-fields"><label class="field">Client ID<input id="client-id" autocomplete="off" placeholder="Your registered app’s client ID"></label><label class="field">Client secret<input id="client-secret" type="password" autocomplete="off" placeholder="Stored securely on this PC"></label></div>${btn('save-credentials','Save credentials')}<span class="hint" style="margin-left:12px">${connection.configured?'Credentials saved.':'One-time setup for this personal build.'}</span></section>`;}
function settings(){return head('Settings','Make this workspace yours.')+`<section class="panel settings-block"><h2>Personalization</h2><div class="settings-row"><div><h3>Artist or studio name</h3><p>Shown in your workspace and release briefs.</p></div><input id="profile-name" aria-label="Artist or studio name" maxlength="80" value="${esc(state.profile.name)}"></div><div class="settings-row"><div><h3>Appearance</h3><p>Choose your preferred workspace theme.</p></div><select id="theme" aria-label="Appearance">${['dark','light','system'].map(v=>`<option value="${v}" ${state.profile.theme===v?'selected':''}>${v[0].toUpperCase()+v.slice(1)}</option>`).join('')}</select></div><div class="actions" style="margin-top:22px">${btn('save-settings','Save preferences',true)}</div></section><section class="panel settings-block"><h2>Your workspace, on your PC</h2><p>Tracks are referenced from their original folders. Release plans, credits, and campaign notes are saved locally. Backups contain workspace metadata and file paths; copy your audio and artwork separately when moving computers.</p><div class="actions">${btn('backup','Export workspace backup')}${btn('restore','Restore a backup')}</div></section><section class="panel settings-block"><h2>Soundcloud Desktop <small>0.1.0</small></h2><p>An independent artist workspace for Windows. Not affiliated with or endorsed by SoundCloud.</p><div class="settings-row"><div><h3>Keyboard shortcuts</h3><p>Ctrl+I · Import audio &nbsp; / &nbsp; Ctrl+N · New release &nbsp; / &nbsp; Space · Play or pause</p></div></div></section>`;}
function uploadPage(){return head('Upload music','From your PC directly to your SoundCloud artist account.',btn('import','＋ Choose audio files',true))+`<div class="panel settings-block"><div class="connection"><div class="connection-icon">↑</div><div><h2>${connection.connected?'Ready for your next track':'Connect your artist account'}</h2><p>${connection.connected?'Choose an audio file below, review its details, then upload.':'Connect SoundCloud once to upload music directly from this app.'}</p></div></div>${!connection.connected?`<div class="actions" style="margin-top:20px">${btn('connect-page','Connect SoundCloud',true)}</div>`:''}</div>${lastUploaded?`<div class="panel settings-block" style="margin-top:18px"><span class="tag green">UPLOAD ACCEPTED</span><h2 style="margin-top:12px">${esc(lastUploaded.title)}</h2><p>${esc(lastUploaded.sharing)} · ${lastUploaded.state==='finished'?'Ready on SoundCloud':'SoundCloud is processing your audio. It may take a few minutes.'}</p>${lastUploaded.url?btn('copy-upload-link','Copy track link'):''} ${btn('open-home','Open SoundCloud ↗')}</div>`:''}<section style="margin-top:24px"><div class="section-head"><h2>Choose a track to upload</h2><small>${state.tracks.length} local tracks</small></div><div class="panel">${state.tracks.length?`<table><thead><tr><th>TRACK</th><th>LAST UPLOAD</th><th></th></tr></thead><tbody>${state.tracks.map(t=>`<tr><td><div class="track-title"><div class="mini-cover">♫</div><div><strong>${esc(t.title)}</strong><small>${esc(t.format)} · ${(t.size/1048576).toFixed(1)} MB</small></div></div></td><td>${t.lastUpload?`<span class="tag green">${esc(t.lastUpload.sharing)}</span><small> ${new Date(t.lastUpload.at).toLocaleDateString()}</small>`:'<small>Not uploaded from this app</small>'}</td><td>${btn('upload-track',t.lastUpload?'Upload another copy':'Upload track',true,t.id)}</td></tr>`).join('')}</tbody></table>`:empty('↑','Start with your audio file','Choose your finished master or drag an audio file into this window. Add the title, artwork, and visibility before uploading.',btn('import','Choose audio files',true))}</div><div class="drop-zone">Drop audio files here · Your originals stay on this PC · Up to 4 GB per track</div></section>`;}
document.body.insertAdjacentHTML('beforeend','<dialog id="upload-dialog"><form id="upload-form"><div id="upload-fields"></div><div class="dialog-actions"><button type="button" id="upload-cancel-dialog">Cancel</button><button class="primary" type="submit">Upload to SoundCloud</button></div></form></dialog>');
let uploadTrackId;
function openUpload(id){if(uploading)return notice('An upload is already in progress.');if(!connection.connected){page='soundcloud';render();return notice('Connect your artist account first, then return to Upload music.');}const t=state.tracks.find(t=>t.id===id);if(!t)return;uploadTrackId=id;$('#upload-fields').innerHTML=`<h2>Upload to SoundCloud</h2><p>${esc(t.format)} · ${(t.size/1048576).toFixed(1)} MB · ${esc(t.title)}</p>${t.lastUpload?'<p class="hint">This file was uploaded before. Continuing creates a separate track on SoundCloud.</p>':''}${field('Track title','title',t.title)}${field('Artist name','artist',state.profile.name==='Your studio'?'':state.profile.name)}<div class="split-fields">${field('Genre','genre',t.genre)}${select('Visibility','sharing',[['private','Private — only you and shared links'],['public','Public — visible to everyone']],'private')}</div><div id="upload-art-preview">${t.art?`<img src="studio://trackart/${t.id}" alt="Track artwork" style="width:70px;height:70px;object-fit:cover;border-radius:6px;margin-top:14px">`:''}</div><button type="button" id="pick-upload-art" style="margin-top:12px">Choose cover artwork</button>${select('Or use release artwork','releaseId',[['','Use track artwork, if added'],...state.releases.filter(r=>r.art).map(r=>[r.id,r.title])],'')}${area('Description / credits','description',[t.notes,t.credits].filter(Boolean).join('\n\n'))}<p class="hint">Upload to ${esc(connection.snapshot?.profile?.username||'your connected account')}. Private is selected by default. Choosing Public publishes the track when SoundCloud finishes processing.</p>`;$('#pick-upload-art').onclick=()=>safely(async()=>{state=await api.trackArtwork(id);const updated=state.tracks.find(t=>t.id===id);if(updated?.art)$('#upload-art-preview').innerHTML=`<img src="studio://trackart/${id}" alt="Track artwork" style="width:70px;height:70px;object-fit:cover;border-radius:6px;margin-top:14px">`;});$('#upload-dialog').showModal();}
$('#upload-cancel-dialog').onclick=()=>$('#upload-dialog').close();
$('#upload-form').onsubmit=e=>{e.preventDefault();if(uploading)return;safely(async()=>{const data=Object.fromEntries(new FormData(e.target));if(!data.title.trim())throw Error('Enter a track title.');uploading=true;$('#upload-dialog').close();$('#upload-status').hidden=false;$('#upload-title').textContent='Uploading '+data.title;$('#upload-percent').textContent='Connecting…';$('#upload-progress').value=0;try{const r=await api.upload(uploadTrackId,data);state=r.state;lastUploaded=r.track;page='upload';render();notice('Upload accepted by SoundCloud. Your track details are saved.');}finally{uploading=false;$('#upload-status').hidden=true;}});};
api.onUpload(data=>{$('#upload-progress').value=data.percent;$('#upload-percent').textContent=data.percent===100?'Processing response…':data.percent+'%';});
$('#cancel-upload').onclick=()=>safely(()=>api.cancelUpload());
function field(label,name,value='',type='text'){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${name==='title'?'required maxlength="180"':''}></label>`;}
function select(label,name,values,value){return `<label class="field">${label}<select name="${name}">${values.map(v=>{const [id,l]=Array.isArray(v)?v:[v,v];return `<option value="${esc(id)}" ${value===id?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;}
function area(label,name,value){return `<label class="field">${label}<textarea name="${name}">${esc(value)}</textarea></label>`;}
function edit(kind,id){const collection={track:'tracks',release:'releases',campaign:'campaigns'}[kind];const item=state[collection].find(t=>t.id===id)||{};editing={kind,id,collection};let content=`<h2>${id?'Edit':'New'} ${kind}</h2><p>${kind==='release'?'Give your next release a clear plan.':kind==='track'?'Keep every version and detail organized.':'Plan the message before you hit publish.'}</p>`+field('Title','title',item.title);
 if(kind==='track')content+=`<div class="split-fields">${select('Status','status',['Draft','Mixing','Mastered','Released'],item.status)}${field('Genre','genre',item.genre)}</div>`+field('SoundCloud link','link',item.link,'url')+area('Credits','credits',item.credits)+area('Studio notes','notes',item.notes);
 if(kind==='release')content+=`<div class="split-fields">${field('Target release date','date',item.date||'','date')}${select('Release type','type',['Single','EP','Album'],item.type||'Single')}</div>`+select('Linked track','trackId',[['','Choose later'],...state.tracks.map(t=>[t.id,t.title])],item.trackId||'')+area('Release notes / credits','notes',item.notes);
 if(kind==='campaign')content+=`<div class="split-fields">${field('Target date','date',item.date||'','date')}${select('Status','status',['Planned','In progress','Done'],item.status||'Planned')}</div>`+select('Channel','channel',['Instagram','TikTok','YouTube','Playlist pitch','Email outreach','General'],item.channel||'General')+field('Contact or outlet','contact',item.contact)+field('Release link','link',item.link,'url')+area('Caption / pitch / notes','caption',item.caption);
 if(id)content+=`<button type="button" class="quiet danger" data-action="delete-item">Remove ${kind} from workspace</button>`;
 $('#dialog-content').innerHTML=content;$('#editor').showModal();}
async function importTracks(drop){const r=drop?await api.dropAudio(drop):await api.importAudio();state=r.state;render();notice(r.count?`${r.count} track${r.count===1?'':'s'} added to your library.`:'No new audio files added. Duplicate files are skipped.');}
async function playTrack(id){const t=state.tracks.find(t=>t.id===id);if(!t)return;current=id;audio.src=`studio://audio/${id}`;$('#now-title').textContent=t.title;$('#now-sub').textContent=`${t.format} · ${t.status}`;if('mediaSession'in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:state.profile.name});await audio.play();}
function toggle(){if(!current){if(state.tracks.length)return playTrack(state.tracks[0].id);return notice('Import a track to start listening.');}return audio.paused?audio.play():audio.pause();}
function skip(delta){if(!state.tracks.length)return;const i=state.tracks.findIndex(t=>t.id===current);return playTrack(state.tracks[(i+delta+state.tracks.length)%state.tracks.length].id);}
const actions={'copy-upload-link':async()=>{if(lastUploaded?.url){await api.copy(lastUploaded.url);notice('Track link copied.');}},'upload-page':()=>{page='upload';render();},'upload-track':id=>openUpload(id),import:()=>importTracks(),'new-release':()=>edit('release'),'new-campaign':()=>edit('campaign'),'edit-track':id=>edit('track',id),'edit-release':id=>edit('release',id),'edit-campaign':id=>edit('campaign',id),'play-track':playTrack,reveal:id=>api.reveal(id),artwork:async id=>{state=await api.artwork(id);render();},'connect-page':()=>{page='soundcloud';render();},'open-home':()=>api.open('home'),'open-upload':()=>api.open('upload'),'open-insights':()=>api.open('insights'),'open-api':()=>api.open('api'),'copy-redirect':async()=>{await api.copy('http://127.0.0.1:49832/callback');notice('Redirect address copied.');},'save-credentials':async()=>{connection=await api.credentials($('#client-id').value.trim(),$('#client-secret').value.trim());render();notice('Credentials encrypted and saved on this PC.');},authorize:async()=>{notice('Finish authorizing in your browser. This window will update when connected.');connection=await api.authorize();render();notice('SoundCloud connected. Your catalog is ready.');},sync:async()=>{notice('Syncing your SoundCloud catalog…');connection=await api.sync();render();notice('Catalog updated.');},disconnect:async()=>{connection=await api.disconnect();render();notice('Account disconnected from this PC.');},'save-settings':async()=>{state.profile.name=$('#profile-name').value.trim()||'Your studio';state.profile.theme=$('#theme').value;await api.theme(state.profile.theme);await save();notice('Preferences saved.');},backup:async()=>{if(await api.backup())notice('Workspace backup exported.');},restore:async()=>{const next=await api.restore();if(next){audio.pause();current=null;state=next;await api.theme(state.profile.theme);render();notice('Workspace restored.');}},'release-copy':async id=>{const r=state.releases.find(r=>r.id===id);await api.copy(`${r.title}\n${state.profile.name} · ${r.type}\nTarget date: ${r.date||'TBD'}\n${r.notes||''}\n\n${r.checks.map(c=>`${c.done?'[x]':'[ ]'} ${c.label}`).join('\n')}`);notice('Release brief copied.');},'copy-campaign':async id=>{const c=state.campaigns.find(c=>c.id===id);await api.copy([c.caption,c.link].filter(Boolean).join('\n\n'));notice('Campaign text copied.');},'delete-item':async()=>{const {collection,id}=editing;state[collection]=state[collection].filter(r=>r.id!==id);if(current===id){audio.pause();current=null;$('#now-title').textContent='Your next great track';$('#now-sub').textContent='Choose a track from your library';}await save();$('#editor').close();notice('Removed from workspace. Original files are preserved.');}};
document.addEventListener('click',e=>{const nav=e.target.closest('[data-page]');if(nav){page=nav.dataset.page;query='';render();return;}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return;}const b=e.target.closest('[data-action]');if(b)safely(async()=>{b.disabled=true;try{await actions[b.dataset.action]?.(b.dataset.id);}finally{b.disabled=false;}});});
document.addEventListener('change',e=>{if(e.target.dataset.check)safely(async()=>{const r=state.releases.find(r=>r.id===e.target.dataset.check);r.checks[Number(e.target.dataset.index)].done=e.target.checked;await save();});});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;const start=e.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(start,start);}});
$('#edit-form').addEventListener('submit',e=>{e.preventDefault();safely(async()=>{const data=Object.fromEntries(new FormData(e.target));data.title=data.title.trim();if(!data.title)throw Error('Add a title first.');const {collection,id,kind}=editing;if(id)Object.assign(state[collection].find(r=>r.id===id),data);else state[collection].unshift({id:uid(),...data,...(kind==='release'?{checks:['Final master approved','Artwork ready','Credits & metadata checked','Uploaded to SoundCloud','Promotion prepared'].map(label=>({label,done:false}))}:{})});await save();$('#editor').close();notice('Saved to your workspace.');});});
$('#cancel').onclick=()=>$('#editor').close();$('#tray').onclick=()=>safely(()=>api.minimize());$('#play').onclick=()=>safely(toggle);$('#previous').onclick=()=>safely(()=>skip(-1));$('#next').onclick=()=>safely(()=>skip(1));
$('#volume').oninput=e=>audio.volume=Number(e.target.value);$('#seek').oninput=e=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(e.target.value)/100*audio.duration;};
const time=n=>Number.isFinite(n)?`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`:'0:00';
audio.ontimeupdate=()=>{$('#elapsed').textContent=time(audio.currentTime);$('#duration').textContent=time(audio.duration);$('#seek').value=Number.isFinite(audio.duration)?audio.currentTime/audio.duration*100:0;};audio.onplay=()=>$('#play').textContent='Ⅱ';audio.onpause=()=>$('#play').textContent='▶';audio.onended=()=>safely(()=>skip(1));audio.onerror=()=>notice('This audio file is unavailable or its codec is not supported. Check the original file in Explorer.');
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='i'){e.preventDefault();safely(()=>importTracks());}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();if(!$('#editor').open&&!$('#upload-dialog').open)edit('release');}if(e.code==='Space'&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)&&!$('#editor').open&&!$('#upload-dialog').open){e.preventDefault();safely(toggle);}});
document.addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('dragging');});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('dragging');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('dragging');safely(()=>importTracks(e.dataTransfer.files));});
if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>safely(toggle));navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',()=>safely(()=>skip(-1)));navigator.mediaSession.setActionHandler('nexttrack',()=>safely(()=>skip(1)));}
matchMedia('(prefers-color-scheme:light)').addEventListener('change',()=>{if(state?.profile.theme==='system')render();});
safely(async()=>{state=await api.read();connection=await api.connection();render();});
